// An app that COMPILES `@blackcode/platform-ui` must also SCAN it for Tailwind.
//
// ---------------------------------------------------------------------------
// THE BUG THIS CLOSES, WHICH WAS LIVE
// ---------------------------------------------------------------------------
// Tailwind v4 auto-detects sources from the project root and skips
// `node_modules`. The platform packages reach an app through a workspace symlink
// under `node_modules`, so `packages/platform-ui/src` was never scanned and
// every utility class living ONLY in that package was never generated.
//
// 151 classes, measured by diffing `apps/issues`'s built stylesheet with and
// without the `@source` line. Among them `data-[state=active]:bg-background` and
// the `group-data-[orientation=…]/tabs` family — the login page's tab switcher
// had no active state — the `file:` and `focus-visible:ring-[3px]` sets on its
// inputs, and `data-[state=open]:animate-accordion-down` on the landing page's
// FAQ. The two most public pages in the product.
//
// ---------------------------------------------------------------------------
// WHY IT SURVIVED, AND WHY IT NEEDED A TEST RATHER THAN A COMMENT
// ---------------------------------------------------------------------------
// Most of the package's classes are ALSO used somewhere in the app that imports
// it, so they were generated by coincidence. The rest degrade into "styled, but
// not quite right" — never into an error, never into a failing build, never into
// anything a type-checker or a linter can see. Nothing in this repo could have
// reported it, and nothing would report its return.
//
// It also gets WORSE as the package gets better: every component moved into the
// shared package brings classes the app no longer uses itself, so the set of
// silently-missing styles grows exactly as the design system is consolidated.
//
// The pairing to remember, and the reason this file is not about CSS but about a
// PAIR: `transpilePackages` makes the TypeScript compile, `@source` makes the
// CSS exist. Neither implies the other, and only one of them fails loudly.
//
// ---------------------------------------------------------------------------
// WHAT THIS DOES NOT CHECK
// ---------------------------------------------------------------------------
// It does not build CSS and diff it — that costs a full Next build per app and
// would be the first minute-long test in the suite. It checks the DECLARATION:
// an app that transpiles the package must point an `@source` at it, and the
// path must resolve to a directory that exists. A wrong-but-existing path would
// pass; a typo'd or stale one will not, and that is the failure that actually
// happens when an app is copied to a new depth.

import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..', '..', '..')
const APPS_ROOT = join(REPO_ROOT, 'apps')

/** The package every app's CSS must scan when it compiles it. */
const UI_PACKAGE = '@blackcode/platform-ui'
const UI_SOURCE_DIR = join(REPO_ROOT, 'packages', 'platform-ui', 'src')

interface App {
  dir: string
  /** Does next.config list the UI package in `transpilePackages`? */
  transpiles: boolean
  /** Every stylesheet in the app that imports Tailwind. */
  tailwindCss: string[]
}

function findTailwindCss(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === '.next' || name === '.turbo') continue
    const p = join(dir, name)
    if (statSync(p).isDirectory()) findTailwindCss(p, out)
    else if (name.endsWith('.css') && /@import\s+["']tailwindcss["']/.test(readFileSync(p, 'utf8'))) {
      out.push(p)
    }
  }
  return out
}

const APPS: App[] = readdirSync(APPS_ROOT, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
  .map((e) => {
    const root = join(APPS_ROOT, e.name)
    const configs = ['next.config.js', 'next.config.mjs', 'next.config.ts']
      .map((f) => join(root, f))
      .filter(existsSync)
    const config = configs.map((f) => readFileSync(f, 'utf8')).join('\n')
    return {
      dir: e.name,
      transpiles: config.includes(UI_PACKAGE),
      tailwindCss: findTailwindCss(root),
    }
  })

describe('the inputs — assert these first, or the check below is theatre', () => {
  it('found app directories', () => {
    expect(APPS.length, 'no app directories found — is APPS_ROOT wrong?').toBeGreaterThan(0)
  })

  // If nothing transpiles the package, every assertion below is vacuously true.
  // That state is reachable — a rename of the package, a next.config moved to a
  // format this file does not read — and it looks exactly like a pass.
  it('at least one app compiles the shared UI package', () => {
    expect(
      APPS.filter((a) => a.transpiles).map((a) => a.dir),
      `no app lists ${UI_PACKAGE} in transpilePackages. Either the package was ` +
        'renamed, or next.config is in a form this test does not read — both of ' +
        'which would make every case below pass by checking nothing.'
    ).not.toEqual([])
  })

  it('the shared UI package has a src directory to scan', () => {
    expect(existsSync(UI_SOURCE_DIR), `${UI_SOURCE_DIR} does not exist`).toBe(true)
  })
})

describe('an app that compiles the shared UI package also scans it', () => {
  const compiling = APPS.filter((a) => a.transpiles)

  it.each(compiling)('apps/$dir', (app) => {
    // An app with no stylesheet has no Tailwind build to be missing classes
    // from. `apps/_template` is in this state today: it lists the package in
    // transpilePackages ahead of using it, and has no CSS at all.
    if (app.tailwindCss.length === 0) return

    const sourced = app.tailwindCss.filter((css) => {
      const text = readFileSync(css, 'utf8')
      for (const m of text.matchAll(/@source\s+["']([^"']+)["']/g)) {
        // Resolve relative to the STYLESHEET, which is how Tailwind resolves it
        // — and the reason this is checked rather than string-matched. Copying
        // an app to a different directory depth silently breaks the path, and
        // the symptom is the same silent one this whole file is about.
        const target = resolve(join(css, '..'), m[1])
        if (target === UI_SOURCE_DIR || UI_SOURCE_DIR.startsWith(target + '/')) return true
      }
      return false
    })

    expect(
      sourced.map((p) => p.slice(REPO_ROOT.length + 1)),
      `apps/${app.dir} compiles ${UI_PACKAGE} but no stylesheet points an ` +
        `@source at packages/platform-ui/src. Tailwind skips node_modules, and ` +
        `the package reaches the app through a workspace symlink there — so ` +
        `every class used ONLY in the package is silently never generated. ` +
        `transpilePackages makes the TypeScript compile; @source makes the CSS ` +
        `exist. Add:  @source "<relative path>/packages/platform-ui/src";`
    ).not.toEqual([])
  })
})
