// An app that COMPILES `@blackcode/platform-ui` must also SCAN it for Tailwind.
//
// ---------------------------------------------------------------------------
// THE BUG THIS CLOSES, WHICH WAS LIVE
// ---------------------------------------------------------------------------
// Tailwind v4 auto-detects sources from the project root and skips
// `node_modules`. The platform packages reach an app through a workspace symlink
// under `node_modules`, so `packages/platform-ui/src` was never scanned and
// every utility class living ONLY in that package was never generated.
//
// 151 classes, measured by diffing `apps/issues`'s built stylesheet with and
// without the `@source` line. Among them `data-[state=active]:bg-background` and
// the `group-data-[orientation=…]/tabs` family — the login page's tab switcher
// had no active state — the `file:` and `focus-visible:ring-[3px]` sets on its
// inputs, and `data-[state=open]:animate-accordion-down` on the landing page's
// FAQ. The two most public pages in the product.
//
// ---------------------------------------------------------------------------
// WHY IT SURVIVED, AND WHY IT NEEDED A TEST RATHER THAN A COMMENT
// ---------------------------------------------------------------------------
// Most of the package's classes are ALSO used somewhere in the app that imports
// it, so they were generated by coincidence. The rest degrade into "styled, but
// not quite right" — never into an error, never into a failing build, never into
// anything a type-checker or a linter can see. Nothing in this repo could have
// reported it, and nothing would report its return.
//
// It also gets WORSE as the package gets better: every component moved into the
// shared package brings classes the app no longer uses itself, so the set of
// silently-missing styles grows exactly as the design system is consolidated.
//
// The pairing to remember, and the reason this file is not about CSS but about a
// PAIR: `transpilePackages` makes the TypeScript compile, `@source` makes the
// CSS exist. Neither implies the other, and only one of them fails loudly.
//
// ---------------------------------------------------------------------------
// IT CHECKS THE STYLESHEET THE APP ACTUALLY IMPORTS. IT DID NOT, UNTIL #11.
// ---------------------------------------------------------------------------
// The first version of this file globbed the app for ANY `.css` containing
// `@import "tailwindcss"` and passed if ANY of them carried an `@source`. It
// never checked that the stylesheet was one the app builds.
//
// So this arrangement passed, on 2026-08-07, while being the exact D-30 bug:
//
//     app/globals.css   imported by app/layout.tsx   @source MISSING
//     app/unused.css    imported by nothing          @source present
//
// 26 passed, 0 failed — with 151 classes silently ungenerated and the login
// page's tab switcher dead. And the realistic path there is not malice: it is a
// stylesheet left behind by a deleted page, or a second CSS entry added for one
// route and later orphaned.
//
// **That makes it the eleventh green-but-inert check in this repo, and the
// second one found in a guard written the same week to close the previous one.**
// Which is the argument for the shape below: reachability from the root layout
// is a fact about the built app, and "a file exists somewhere in the tree" is
// not.
//
// ---------------------------------------------------------------------------
// WHAT THIS DOES NOT CHECK
// ---------------------------------------------------------------------------
// It does not build CSS and diff it — that costs a full Next build per app and
// would be the first minute-long test in the suite. It checks the DECLARATION:
// an app that transpiles the package must point an `@source` at it from a
// stylesheet its root layout reaches, and the path must resolve to a directory
// that exists. A wrong-but-existing path would pass; a typo'd or stale one will
// not, and that is the failure that actually happens when an app is copied to a
// new depth.

import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..', '..', '..')
const APPS_ROOT = join(REPO_ROOT, 'apps')

/** The package every app's CSS must scan when it compiles it. */
const UI_PACKAGE = '@blackcode/platform-ui'
const UI_SOURCE_DIR = join(REPO_ROOT, 'packages', 'platform-ui', 'src')

interface App {
  dir: string
  /** Does next.config list the UI package in `transpilePackages`? */
  transpiles: boolean
  /**
   * Every stylesheet the ROOT LAYOUT reaches — what the app actually builds.
   *
   * NOT filtered to the ones that import Tailwind, and that distinction cost a
   * false positive when this was written: Tailwind inlines `@import`, so a
   * `globals.css` that imports Tailwind and then `@import "./theme-tokens.css"`
   * has ONE build, and the `@source` may legitimately live in either file.
   * Filtering to Tailwind-importing files rejected the split arrangement — a
   * guard failing on correct writing, which is what D-37 is about.
   */
  reachableCss: string[]
  /** True when something in `reachableCss` imports Tailwind at all. */
  buildsTailwind: boolean
  /** Tailwind stylesheets anywhere in the tree. Only used to detect orphans. */
  allCss: string[]
  /** The root layout, or null when the app has none. */
  rootLayout: string | null
}

/** Every `.css` under `dir` that imports Tailwind, wherever it sits. */
function findTailwindCss(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === '.next' || name === '.turbo') continue
    const p = join(dir, name)
    if (statSync(p).isDirectory()) findTailwindCss(p, out)
    else if (name.endsWith('.css') && /@import\s+["']tailwindcss["']/.test(readFileSync(p, 'utf8'))) {
      out.push(p)
    }
  }
  return out
}

/** `app/layout.tsx` or `src/app/layout.tsx`, in any of the four extensions. */
function findRootLayout(appRoot: string): string | null {
  for (const base of ['app', join('src', 'app')]) {
    for (const ext of ['tsx', 'jsx', 'ts', 'js']) {
      const p = join(appRoot, base, `layout.${ext}`)
      if (existsSync(p)) return p
    }
  }
  return null
}

/**
 * The stylesheets a file pulls in, transitively.
 *
 * Two hops, because both are real: a module imports a stylesheet
 * (`import './globals.css'`), and a stylesheet `@import`s another one. An app
 * that splits its tokens into `theme.css` and imports it from `globals.css` is
 * a normal arrangement, and a check that could not see through it would fail on
 * correct code — D-37.
 *
 * Bare specifiers are skipped deliberately: `@import "tailwindcss"` and
 * `@import "tw-animate-css"` resolve into node_modules, which is not where an
 * app's own `@source` can live.
 */
function reachableStylesheets(entry: string): string[] {
  const seen = new Set<string>()
  const out: string[] = []

  const visitCss = (file: string) => {
    if (seen.has(file) || !existsSync(file)) return
    seen.add(file)
    out.push(file)
    const src = readFileSync(file, 'utf8')
    for (const m of src.matchAll(/@import\s+["']([^"']+)["']/g)) {
      const spec = m[1]
      if (!spec.startsWith('.') && !spec.startsWith('/')) continue
      visitCss(resolve(join(file, '..'), spec))
    }
  }

  const src = readFileSync(entry, 'utf8')
  for (const m of src.matchAll(/import\s+["']([^"']+\.css)["']/g)) {
    const spec = m[1]
    if (!spec.startsWith('.')) continue
    visitCss(resolve(join(entry, '..'), spec))
  }
  return out
}

const APPS: App[] = readdirSync(APPS_ROOT, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
  .map((e) => {
    const root = join(APPS_ROOT, e.name)
    const configs = ['next.config.js', 'next.config.mjs', 'next.config.ts']
      .map((f) => join(root, f))
      .filter(existsSync)
    const config = configs.map((f) => readFileSync(f, 'utf8')).join('\n')
    const allCss = findTailwindCss(root)
    const rootLayout = findRootLayout(root)
    const reachable = rootLayout ? reachableStylesheets(rootLayout) : []
    return {
      dir: e.name,
      transpiles: config.includes(UI_PACKAGE),
      reachableCss: reachable,
      buildsTailwind: reachable.some((p) => allCss.includes(p)),
      allCss,
      rootLayout,
    }
  })

describe('the inputs — assert these first, or the check below is theatre', () => {
  it('found app directories', () => {
    expect(APPS.length, 'no app directories found — is APPS_ROOT wrong?').toBeGreaterThan(0)
  })

  // If nothing transpiles the package, every assertion below is vacuously true.
  // That state is reachable — a rename of the package, a next.config moved to a
  // format this file does not read — and it looks exactly like a pass.
  it('at least one app compiles the shared UI package', () => {
    expect(
      APPS.filter((a) => a.transpiles).map((a) => a.dir),
      `no app lists ${UI_PACKAGE} in transpilePackages. Either the package was ` +
        'renamed, or next.config is in a form this test does not read — both of ' +
        'which would make every case below pass by checking nothing.'
    ).not.toEqual([])
  })

  it('the shared UI package has a src directory to scan', () => {
    expect(existsSync(UI_SOURCE_DIR), `${UI_SOURCE_DIR} does not exist`).toBe(true)
  })
})

describe('an app that compiles the shared UI package also scans it', () => {
  const compiling = APPS.filter((a) => a.transpiles)

  it.each(compiling)('apps/$dir', (app) => {
    // An app with no stylesheet at all has no Tailwind build to be missing
    // classes from. `apps/_scaffold` is in this state today: it lists the
    // package in transpilePackages ahead of using it, and has no CSS.
    if (app.allCss.length === 0) return

    // It HAS Tailwind stylesheets and the root layout reaches none of them. That
    // is not a pass — it is this check being unable to see what the app builds,
    // and the corollary in CLAUDE.md is that a check which cannot run must skip
    // LOUDLY rather than silently. Realistically it means the layout was moved,
    // or the global stylesheet is imported somewhere this resolver does not
    // follow; either way the answer below would be about nothing.
    expect(
      app.buildsTailwind,
      `apps/${app.dir} has Tailwind stylesheets (${app.allCss
        .map((p) => p.slice(REPO_ROOT.length + 1))
        .join(', ')}) but its root layout ` +
        `(${app.rootLayout ? app.rootLayout.slice(REPO_ROOT.length + 1) : 'NOT FOUND'}) ` +
        'reaches none of them, so this check cannot see the CSS the app actually ' +
        'builds. Import the global stylesheet from the root layout, or teach ' +
        'reachableStylesheets() how this app wires it up.'
    ).toBe(true)

    const sourced = app.reachableCss.filter((css) => {
      const text = readFileSync(css, 'utf8')
      for (const m of text.matchAll(/@source\s+["']([^"']+)["']/g)) {
        // Resolve relative to the STYLESHEET, which is how Tailwind resolves it
        // — and the reason this is checked rather than string-matched. Copying
        // an app to a different directory depth silently breaks the path, and
        // the symptom is the same silent one this whole file is about.
        const target = resolve(join(css, '..'), m[1])
        if (target === UI_SOURCE_DIR || UI_SOURCE_DIR.startsWith(target + '/')) return true
      }
      return false
    })

    expect(
      sourced.map((p) => p.slice(REPO_ROOT.length + 1)),
      `apps/${app.dir} compiles ${UI_PACKAGE} but none of the stylesheets its ` +
        `root layout actually reaches ` +
        `(${app.reachableCss.map((p) => p.slice(REPO_ROOT.length + 1)).join(', ')}) ` +
        `points an @source at packages/platform-ui/src. Tailwind skips ` +
        `node_modules, and the package reaches the app through a workspace ` +
        `symlink there — so every class used ONLY in the package is silently ` +
        `never generated. transpilePackages makes the TypeScript compile; ` +
        `@source makes the CSS exist. Add:  @source "<relative path>/packages/platform-ui/src";` +
        (app.allCss.length > app.reachableCss.length
          ? `\n\nNOTE: this app has other Tailwind stylesheets that the root ` +
            `layout does NOT import, and they are deliberately not counted. An ` +
            `@source in an orphan stylesheet generates nothing.`
          : '')
    ).not.toEqual([])
  })
})
