// Package skill renders and locates the agent skill file that `bk skill install`
// writes.
//
// The design constraint that shapes everything here: the skill must contain NO
// facts that can rot. It is a pointer — "run `bk guide`, run `bk meta`" — not a
// copy. That is why it is identical for every user and essentially never needs
// to change, and why a stale copy is harmless rather than actively misleading.
//
// The only thing that varies is the trailing version stamp, which `bk skill
// check` reads to tell whether the installed file came from this binary.
package skill

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

//go:embed template.md
var template string

// Name is the skill's directory/identifier under .claude/skills/.
const Name = "blackcode-issues"

// stampRe matches the trailing provenance comment, e.g.
// `<!-- generated by bk skill install · cli 1.9.0 · do not edit -->`.
var stampRe = regexp.MustCompile(`<!--\s*generated by bk skill install\s*·\s*cli\s+([^\s·]+)\s*·[^>]*-->`)

// Render returns the skill file content stamped with the running CLI version.
func Render(version string) string {
	return strings.TrimSpace(template) +
		fmt.Sprintf("\n\n<!-- generated by bk skill install · cli %s · do not edit -->\n", version)
}

// StampedVersion extracts the CLI version from an installed skill file's stamp.
// Returns "" when the file has no stamp (hand-written, or from a pre-1.9 CLI).
func StampedVersion(content string) string {
	if m := stampRe.FindStringSubmatch(content); m != nil {
		return m[1]
	}
	return ""
}

// --- AGENTS.md container -----------------------------------------------------

const (
	agentsBegin = "<!-- BEGIN blackcode-issues (managed by bk skill install) -->"
	agentsEnd   = "<!-- END blackcode-issues -->"
)

// RenderAgentsSection returns the delimited `## blackcode issues` block that
// `bk skill install --format agents-md` writes into ./AGENTS.md. Same content,
// different container — the markers let a re-run update it in place instead of
// appending a second copy.
func RenderAgentsSection(version string) string {
	body := strings.TrimSpace(template)
	// Drop the YAML front matter — AGENTS.md is prose, not a skill manifest.
	if strings.HasPrefix(body, "---") {
		if i := strings.Index(body[3:], "\n---"); i >= 0 {
			body = strings.TrimSpace(body[3+i+4:])
		}
	}
	// Demote every heading one level so `# blackcode issues` nests under the
	// host document's structure.
	lines := strings.Split(body, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "#") {
			lines[i] = "#" + l
		}
	}
	return fmt.Sprintf("%s\n%s\n\n<!-- bk %s -->\n%s\n",
		agentsBegin, strings.Join(lines, "\n"), version, agentsEnd)
}

// UpsertAgentsSection replaces the delimited block in doc, or appends it when
// there isn't one yet.
func UpsertAgentsSection(doc, section string) string {
	start := strings.Index(doc, agentsBegin)
	end := strings.Index(doc, agentsEnd)
	if start >= 0 && end > start {
		return doc[:start] + strings.TrimRight(section, "\n") + doc[end+len(agentsEnd):]
	}
	if strings.TrimSpace(doc) == "" {
		return section
	}
	return strings.TrimRight(doc, "\n") + "\n\n" + section
}

// --- target resolution -------------------------------------------------------

// DefaultDir picks where the skill file goes:
//
//	./.claude/skills/blackcode-issues/   when a .claude/ exists in cwd or an
//	                                     ancestor (project-local install)
//	~/.claude/skills/blackcode-issues/   otherwise (user-global install)
//
// Preferring the project-local directory matters: an agent working in a repo
// should get the skill that repo's collaborators see, not one user's global copy.
func DefaultDir() (string, error) {
	if root, ok := findClaudeDir(); ok {
		return filepath.Join(root, "skills", Name), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".claude", "skills", Name), nil
}

// findClaudeDir walks up from the working directory looking for a `.claude`
// directory, returning its path.
func findClaudeDir() (string, bool) {
	dir, err := os.Getwd()
	if err != nil {
		return "", false
	}
	for {
		candidate := filepath.Join(dir, ".claude")
		if fi, err := os.Stat(candidate); err == nil && fi.IsDir() {
			return candidate, true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

// FilePath returns the SKILL.md path inside a skill directory.
func FilePath(dir string) string {
	return filepath.Join(dir, "SKILL.md")
}
