// Package skill renders and locates the agent skill file that `bk skill install`
// writes.
//
// The design constraint that shapes everything here: the skill must contain NO
// facts that can rot. It is a pointer — "run `bk guide`, run `bk meta`" — not a
// copy. That is why it is identical for every user and essentially never needs
// to change, and why a stale copy is harmless rather than actively misleading.
//
// The only thing that varies is the trailing version stamp, which `bk skill
// check` reads to tell whether the installed file came from this binary.
//
// OWNERSHIP. `bk skill sync` is the one command agents are told to run
// unprompted, so writing must never destroy something a human wrote. The block
// bk owns is delimited by markers; anything outside them — added front matter,
// team rules appended below — is preserved across every install and sync. A file
// with neither the markers nor the legacy stamp was NOT written by bk, and bk
// refuses to touch it (see Classify / ErrForeign).
package skill

import (
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

//go:embed template.md
var template string

// Name is the skill's directory/identifier under .claude/skills/.
const Name = "blackcode-issues"

// stampRe matches the trailing provenance comment, e.g.
// `<!-- generated by bk skill install · cli 1.9.0 · do not edit -->`.
var stampRe = regexp.MustCompile(`<!--\s*generated by bk skill install\s*·\s*cli\s+([^\s·]+)\s*·[^>]*-->`)

// Render returns a complete SKILL.md: the YAML front matter, then the delimited
// block bk owns.
//
// The front matter is deliberately OUTSIDE the markers. Skill loaders require it
// at the very top of the file, so a leading HTML comment would break parsing —
// and it also means a user may retitle or re-describe the skill without bk
// reverting it on the next sync.
func Render(version string) string {
	fm, body := splitFrontMatter(strings.TrimSpace(template))
	if fm == "" {
		return renderBlock(body, version)
	}
	return fm + "\n\n" + renderBlock(body, version)
}

// renderBlock returns the marked, version-stamped region.
func renderBlock(body, version string) string {
	return fmt.Sprintf("%s\n%s\n\n<!-- generated by bk skill install · cli %s · do not edit -->\n%s\n",
		blockBegin, strings.TrimSpace(body), version, blockEnd)
}

// splitFrontMatter separates a leading `---` YAML block from the body.
func splitFrontMatter(doc string) (frontMatter, body string) {
	if !strings.HasPrefix(doc, "---") {
		return "", doc
	}
	i := strings.Index(doc[3:], "\n---")
	if i < 0 {
		return "", doc
	}
	end := 3 + i + 4
	return strings.TrimSpace(doc[:end]), strings.TrimSpace(doc[end:])
}

// Ownership says who wrote the file bk is about to overwrite.
type Ownership int

const (
	// Absent — no file, or an empty one. Safe to create.
	Absent Ownership = iota
	// Managed — carries bk's markers. Only the marked region is replaced.
	Managed
	// Legacy — written by bk 1.9.0, which stamped but did not delimit. Every
	// byte of it came from bk, so it is safe to rewrite wholesale (which also
	// migrates it to the marked format).
	Legacy
	// Foreign — neither marker nor stamp. A human wrote this. Never touch it.
	Foreign
)

// ErrForeign is returned when the target was not written by bk.
var ErrForeign = errors.New("skill file was not written by bk")

// Classify reports who owns an existing skill file's content.
func Classify(content string) Ownership {
	if strings.TrimSpace(content) == "" {
		return Absent
	}
	if strings.Contains(content, blockBegin) && strings.Contains(content, blockEnd) {
		return Managed
	}
	if stampRe.MatchString(content) {
		return Legacy
	}
	return Foreign
}

// UpsertSkillFile returns the new SKILL.md content for an existing file.
//
// It returns ErrForeign — and never a partial write — when the file was written
// by someone other than bk. Callers decide what that means: `install` refuses
// unless --force, `sync` leaves the file alone and warns.
func UpsertSkillFile(existing, version string) (string, error) {
	switch Classify(existing) {
	case Absent, Legacy:
		return Render(version), nil
	case Managed:
		start := strings.Index(existing, blockBegin)
		end := strings.Index(existing, blockEnd)
		if start < 0 || end < start {
			return "", ErrForeign
		}
		_, body := splitFrontMatter(strings.TrimSpace(template))
		block := strings.TrimRight(renderBlock(body, version), "\n")
		return existing[:start] + block + existing[end+len(blockEnd):], nil
	default:
		return "", ErrForeign
	}
}

// StampedVersion extracts the CLI version from an installed skill file's stamp.
// Returns "" when the file has no stamp (hand-written, or from a pre-1.9 CLI).
func StampedVersion(content string) string {
	if m := stampRe.FindStringSubmatch(content); m != nil {
		return m[1]
	}
	return ""
}

// --- AGENTS.md container -----------------------------------------------------

// Markers delimiting the region bk owns. Shared by SKILL.md and the AGENTS.md
// section so both containers behave identically: a re-run replaces what is
// between them and leaves everything else alone.
const (
	blockBegin = "<!-- BEGIN blackcode-issues (managed by bk skill install) -->"
	blockEnd   = "<!-- END blackcode-issues -->"
)

// BlockBegin and BlockEnd are exported so commands can print them verbatim: the
// fix for a foreign file is "paste these two lines in", which is only actionable
// if the error message contains the exact strings.
const (
	BlockBegin = blockBegin
	BlockEnd   = blockEnd
)

// RenderAgentsSection returns the delimited `## blackcode issues` block that
// `bk skill install --format agents-md` writes into ./AGENTS.md. Same content,
// different container — the markers let a re-run update it in place instead of
// appending a second copy.
func RenderAgentsSection(version string) string {
	// Drop the YAML front matter — AGENTS.md is prose, not a skill manifest.
	_, body := splitFrontMatter(strings.TrimSpace(template))
	// Demote every heading one level so `# blackcode issues` nests under the
	// host document's structure.
	lines := strings.Split(body, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "#") {
			lines[i] = "#" + l
		}
	}
	return fmt.Sprintf("%s\n%s\n\n<!-- bk %s -->\n%s\n",
		blockBegin, strings.Join(lines, "\n"), version, blockEnd)
}

// UpsertAgentsSection replaces the delimited block in doc, or appends it when
// there isn't one yet.
func UpsertAgentsSection(doc, section string) string {
	start := strings.Index(doc, blockBegin)
	end := strings.Index(doc, blockEnd)
	if start >= 0 && end > start {
		return doc[:start] + strings.TrimRight(section, "\n") + doc[end+len(blockEnd):]
	}
	if strings.TrimSpace(doc) == "" {
		return section
	}
	return strings.TrimRight(doc, "\n") + "\n\n" + section
}

// --- target resolution -------------------------------------------------------

// DefaultDir picks where the skill file goes:
//
//	./.claude/skills/blackcode-issues/   when a .claude/ exists in cwd or an
//	                                     ancestor (project-local install)
//	~/.claude/skills/blackcode-issues/   otherwise (user-global install)
//
// Preferring the project-local directory matters: an agent working in a repo
// should get the skill that repo's collaborators see, not one user's global copy.
func DefaultDir() (string, error) {
	if root, ok := findClaudeDir(); ok {
		return filepath.Join(root, "skills", Name), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".claude", "skills", Name), nil
}

// findClaudeDir walks up from the working directory looking for a `.claude`
// directory, returning its path.
func findClaudeDir() (string, bool) {
	dir, err := os.Getwd()
	if err != nil {
		return "", false
	}
	for {
		candidate := filepath.Join(dir, ".claude")
		if fi, err := os.Stat(candidate); err == nil && fi.IsDir() {
			return candidate, true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

// FilePath returns the SKILL.md path inside a skill directory.
func FilePath(dir string) string {
	return filepath.Join(dir, "SKILL.md")
}
