package skill

import (
	"errors"
	"strings"
	"testing"
)

// The skill's one design rule: it contains NO facts that can rot. If someone
// adds a status value, a byte cap or an HTTP route to the template, a stale
// installed copy starts actively misleading agents instead of merely pointing
// at the right commands.
func TestTemplateContainsNoRottableFacts(t *testing.T) {
	banned := []string{
		"100MB", "on_track", "at_risk", "backlog", "in_progress",
		"/api/", "Bearer", "openapi", "P0", "P1",
	}
	for _, b := range banned {
		if strings.Contains(template, b) {
			t.Errorf("skill template mentions %q — it must only point at `bk guide` / `bk meta`", b)
		}
	}
	if n := len(strings.Split(strings.TrimSpace(template), "\n")); n > 40 {
		t.Errorf("skill template is %d lines; keep it ~30 — specifics belong behind `bk guide`", n)
	}
}

func TestRenderRoundTripsTheVersionStamp(t *testing.T) {
	out := Render("1.9.0")
	if got := StampedVersion(out); got != "1.9.0" {
		t.Errorf("StampedVersion(Render(1.9.0)) = %q, want 1.9.0", got)
	}
	if StampedVersion("no stamp here") != "" {
		t.Error("an unstamped file must report an empty version, not a false match")
	}
}

func TestUpsertAgentsSectionReplacesInPlace(t *testing.T) {
	doc := "# My project\n\nSome prose.\n"
	first := UpsertAgentsSection(doc, RenderAgentsSection("1.9.0"))
	if !strings.Contains(first, "My project") {
		t.Fatal("upsert dropped the host document")
	}
	second := UpsertAgentsSection(first, RenderAgentsSection("1.9.1"))
	if strings.Count(second, blockBegin) != 1 {
		t.Errorf("re-running install duplicated the section (%d copies)", strings.Count(second, blockBegin))
	}
	if !strings.Contains(second, "1.9.1") || strings.Contains(second, "bk 1.9.0 -->") {
		t.Error("re-running install did not update the version stamp in place")
	}
	// Headings must be demoted so the block nests under the host document.
	if strings.Contains(second, "\n# blackcode issues") {
		t.Error("the AGENTS.md section kept a top-level heading")
	}
}

// --- ownership: bk must never destroy what a human wrote ---------------------
//
// `bk skill sync` is the one command agents run unprompted, so a destructive
// write here would silently delete a team's hand-written rules the first time an
// agent auto-recovered from a version bump — and nobody would know why the agent
// started behaving differently. Before v1.9.1 it did exactly that.

const handWritten = `---
name: blackcode-issues
---
# Our team's rules
- Always use the "acme" workspace.
- Ask Dana before deleting anything.
`

func TestClassify(t *testing.T) {
	cases := []struct {
		name    string
		content string
		want    Ownership
	}{
		{"empty", "", Absent},
		{"whitespace only", "\n\n  \n", Absent},
		{"hand-written", handWritten, Foreign},
		{"bk 1.9.0 output (stamped, unmarked)", "# blackcode issues\n\n<!-- generated by bk skill install · cli 1.9.0 · do not edit -->\n", Legacy},
		{"current output", Render("v1.9.1"), Managed},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := Classify(c.content); got != c.want {
				t.Errorf("Classify() = %v, want %v", got, c.want)
			}
		})
	}
}

func TestUpsertRefusesForeignFile(t *testing.T) {
	if _, err := UpsertSkillFile(handWritten, "v1.9.1"); !errors.Is(err, ErrForeign) {
		t.Fatalf("UpsertSkillFile on a hand-written file = %v, want ErrForeign", err)
	}
}

// A legacy file was written entirely by bk 1.9.0, so rewriting it is safe — and
// it migrates the file to the marked format so future syncs are surgical.
func TestUpsertMigratesLegacyFile(t *testing.T) {
	legacy := "# blackcode issues\n\n<!-- generated by bk skill install · cli 1.9.0 · do not edit -->\n"
	got, err := UpsertSkillFile(legacy, "v1.9.1")
	if err != nil {
		t.Fatalf("UpsertSkillFile: %v", err)
	}
	if Classify(got) != Managed {
		t.Error("a migrated legacy file should now be Managed")
	}
	if StampedVersion(got) != "v1.9.1" {
		t.Errorf("stamp = %q, want v1.9.1", StampedVersion(got))
	}
}

// The whole point of the markers: a user may write around bk's block, and every
// future sync must leave their words alone while refreshing bk's.
func TestUpsertPreservesContentAroundTheBlock(t *testing.T) {
	withExtras := "---\nname: blackcode-issues\ndescription: our tweaked description\n---\n\n" +
		BlockBegin + "\nold generated body\n\n<!-- generated by bk skill install · cli 1.9.0 · do not edit -->\n" + BlockEnd +
		"\n\n## Team additions\n- Ask Dana before deleting anything.\n"

	got, err := UpsertSkillFile(withExtras, "v1.9.1")
	if err != nil {
		t.Fatalf("UpsertSkillFile: %v", err)
	}
	for _, keep := range []string{"our tweaked description", "## Team additions", "Ask Dana before deleting anything"} {
		if !strings.Contains(got, keep) {
			t.Errorf("sync dropped user content: %q", keep)
		}
	}
	if strings.Contains(got, "old generated body") {
		t.Error("sync did not refresh the managed block")
	}
	if StampedVersion(got) != "v1.9.1" {
		t.Errorf("stamp = %q, want v1.9.1", StampedVersion(got))
	}
	if n := strings.Count(got, BlockBegin); n != 1 {
		t.Errorf("got %d begin markers, want exactly 1", n)
	}
}

// Skill loaders require YAML front matter at the very top; a leading HTML
// comment would break parsing.
func TestRenderKeepsFrontMatterFirst(t *testing.T) {
	out := Render("v1.9.1")
	if !strings.HasPrefix(out, "---\n") {
		t.Fatalf("Render() must start with front matter, got: %.40q", out)
	}
	if strings.Index(out, BlockBegin) < strings.Index(out, "\n---\n") {
		t.Error("the managed block must come after the front matter")
	}
}
